name: Flask test suite
run-name: ${{ github.actor }} is building symmetry ðŸš€
on: [push]
jobs:
  Test_API_endpoints:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd api
          pip install -r requirements.txt
          python -m nltk.downloader punkt

      - name: Run Pytest
        run: pytest
      
      - name: Install PyInstaller
        run: pip install pyinstaller
      
      - name: Build with PyInstaller
        run: pyinstaller -F api/flaskr/app.py

      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
